name: Deploy to Firebase Hosting on Main Branch
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies and build
      - run: |
          echo "CI=false" >> $GITHUB_ENV
          npm ci && npm run build

      # Step 3: Deploy to Firebase Production (live) channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAI_WALEY }}
          channelId: live  # Deploy to the live channel (Production)
          projectId: test-61416
